# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IP_Cheat.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1038, 394)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1038, 394))
        MainWindow.setMaximumSize(QtCore.QSize(1038, 394))
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 57, 1031, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(200, 20))
        self.label_3.setMaximumSize(QtCore.QSize(200, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.need_scan_port_T = QtWidgets.QPlainTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.need_scan_port_T.sizePolicy().hasHeightForWidth())
        self.need_scan_port_T.setSizePolicy(sizePolicy)
        self.need_scan_port_T.setMinimumSize(QtCore.QSize(296, 30))
        self.need_scan_port_T.setMaximumSize(QtCore.QSize(296, 30))
        self.need_scan_port_T.setObjectName("need_scan_port_T")
        self.gridLayout_2.addWidget(self.need_scan_port_T, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(200, 20))
        self.label_8.setMaximumSize(QtCore.QSize(200, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.port_type_C = QtWidgets.QComboBox(self.layoutWidget)
        self.port_type_C.setMinimumSize(QtCore.QSize(80, 28))
        self.port_type_C.setMaximumSize(QtCore.QSize(80, 28))
        self.port_type_C.setObjectName("port_type_C")
        self.port_type_C.addItem("")
        self.port_type_C.addItem("")
        self.gridLayout_2.addWidget(self.port_type_C, 0, 3, 1, 1)
        self.host_choice = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.host_choice.sizePolicy().hasHeightForWidth())
        self.host_choice.setSizePolicy(sizePolicy)
        self.host_choice.setMinimumSize(QtCore.QSize(100, 20))
        self.host_choice.setMaximumSize(QtCore.QSize(100, 20))
        self.host_choice.setChecked(True)
        self.host_choice.setObjectName("host_choice")
        self.gridLayout_2.addWidget(self.host_choice, 0, 4, 1, 1)
        self.port_choice = QtWidgets.QRadioButton(self.layoutWidget)
        self.port_choice.setMinimumSize(QtCore.QSize(100, 20))
        self.port_choice.setMaximumSize(QtCore.QSize(100, 20))
        self.port_choice.setCheckable(True)
        self.port_choice.setChecked(False)
        self.port_choice.setObjectName("port_choice")
        self.gridLayout_2.addWidget(self.port_choice, 0, 5, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 105, 1021, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.live_host = QtWidgets.QComboBox(self.layoutWidget1)
        self.live_host.setMinimumSize(QtCore.QSize(0, 28))
        self.live_host.setMaximumSize(QtCore.QSize(16777215, 28))
        self.live_host.setObjectName("live_host")
        self.gridLayout_6.addWidget(self.live_host, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(200, 20))
        self.label_4.setMaximumSize(QtCore.QSize(200, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 2, 1, 1)
        self.ip_and_open_port = QtWidgets.QComboBox(self.layoutWidget1)
        self.ip_and_open_port.setMinimumSize(QtCore.QSize(0, 28))
        self.ip_and_open_port.setMaximumSize(QtCore.QSize(16777215, 28))
        self.ip_and_open_port.setObjectName("ip_and_open_port")
        self.gridLayout_6.addWidget(self.ip_and_open_port, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 20))
        self.label.setMaximumSize(QtCore.QSize(200, 20))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.gw = QtWidgets.QComboBox(self.layoutWidget1)
        self.gw.setMinimumSize(QtCore.QSize(0, 28))
        self.gw.setMaximumSize(QtCore.QSize(16777215, 28))
        self.gw.setObjectName("gw")
        self.gridLayout_6.addWidget(self.gw, 0, 6, 1, 1)
        self.gwcheck = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gwcheck.sizePolicy().hasHeightForWidth())
        self.gwcheck.setSizePolicy(sizePolicy)
        self.gwcheck.setText("")
        self.gwcheck.setObjectName("gwcheck")
        self.gridLayout_6.addWidget(self.gwcheck, 0, 5, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget2.setGeometry(QtCore.QRect(9, 153, 1021, 40))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cheat_host_one_C = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cheat_host_one_C.sizePolicy().hasHeightForWidth())
        self.cheat_host_one_C.setSizePolicy(sizePolicy)
        self.cheat_host_one_C.setMinimumSize(QtCore.QSize(0, 28))
        self.cheat_host_one_C.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cheat_host_one_C.setObjectName("cheat_host_one_C")
        self.gridLayout_4.addWidget(self.cheat_host_one_C, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setMinimumSize(QtCore.QSize(200, 20))
        self.label_6.setMaximumSize(QtCore.QSize(200, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)
        self.cheat_host_two_C = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cheat_host_two_C.sizePolicy().hasHeightForWidth())
        self.cheat_host_two_C.setSizePolicy(sizePolicy)
        self.cheat_host_two_C.setMinimumSize(QtCore.QSize(0, 28))
        self.cheat_host_two_C.setMaximumSize(QtCore.QSize(16777215, 28))
        self.cheat_host_two_C.setObjectName("cheat_host_two_C")
        self.gridLayout_4.addWidget(self.cheat_host_two_C, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(200, 20))
        self.label_5.setMaximumSize(QtCore.QSize(200, 20))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.ARP_cheat_B = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARP_cheat_B.sizePolicy().hasHeightForWidth())
        self.ARP_cheat_B.setSizePolicy(sizePolicy)
        self.ARP_cheat_B.setObjectName("ARP_cheat_B")
        self.gridLayout_4.addWidget(self.ARP_cheat_B, 0, 6, 1, 1)
        self.ARP_higher_B = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARP_higher_B.sizePolicy().hasHeightForWidth())
        self.ARP_higher_B.setSizePolicy(sizePolicy)
        self.ARP_higher_B.setObjectName("ARP_higher_B")
        self.gridLayout_4.addWidget(self.ARP_higher_B, 0, 7, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 199, 1021, 42))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.attack_type_C = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attack_type_C.sizePolicy().hasHeightForWidth())
        self.attack_type_C.setSizePolicy(sizePolicy)
        self.attack_type_C.setMinimumSize(QtCore.QSize(150, 28))
        self.attack_type_C.setMaximumSize(QtCore.QSize(150, 28))
        self.attack_type_C.setObjectName("attack_type_C")
        self.attack_type_C.addItem("")
        self.attack_type_C.addItem("")
        self.attack_type_C.addItem("")
        self.gridLayout_5.addWidget(self.attack_type_C, 0, 3, 1, 1)
        self.flood_port_T = QtWidgets.QPlainTextEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flood_port_T.sizePolicy().hasHeightForWidth())
        self.flood_port_T.setSizePolicy(sizePolicy)
        self.flood_port_T.setMaximumSize(QtCore.QSize(50, 30))
        self.flood_port_T.setObjectName("flood_port_T")
        self.gridLayout_5.addWidget(self.flood_port_T, 0, 5, 1, 1)
        self.attack_ip_T = QtWidgets.QPlainTextEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attack_ip_T.sizePolicy().hasHeightForWidth())
        self.attack_ip_T.setSizePolicy(sizePolicy)
        self.attack_ip_T.setMinimumSize(QtCore.QSize(160, 30))
        self.attack_ip_T.setMaximumSize(QtCore.QSize(160, 30))
        self.attack_ip_T.setObjectName("attack_ip_T")
        self.gridLayout_5.addWidget(self.attack_ip_T, 0, 1, 1, 1)
        self.start_attack_B = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_attack_B.sizePolicy().hasHeightForWidth())
        self.start_attack_B.setSizePolicy(sizePolicy)
        self.start_attack_B.setObjectName("start_attack_B")
        self.gridLayout_5.addWidget(self.start_attack_B, 0, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(150, 20))
        self.label_13.setMaximumSize(QtCore.QSize(150, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(150, 20))
        self.label_14.setMaximumSize(QtCore.QSize(150, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(200, 20))
        self.label_12.setMaximumSize(QtCore.QSize(200, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget4.setGeometry(QtCore.QRect(9, 247, 1021, 42))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(150, 20))
        self.label_10.setMaximumSize(QtCore.QSize(150, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.start_ip_cheat_B = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_ip_cheat_B.sizePolicy().hasHeightForWidth())
        self.start_ip_cheat_B.setSizePolicy(sizePolicy)
        self.start_ip_cheat_B.setObjectName("start_ip_cheat_B")
        self.gridLayout_3.addWidget(self.start_ip_cheat_B, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(200, 20))
        self.label_9.setMaximumSize(QtCore.QSize(200, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.trust_ip_C = QtWidgets.QComboBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trust_ip_C.sizePolicy().hasHeightForWidth())
        self.trust_ip_C.setSizePolicy(sizePolicy)
        self.trust_ip_C.setMinimumSize(QtCore.QSize(150, 28))
        self.trust_ip_C.setMaximumSize(QtCore.QSize(160, 28))
        self.trust_ip_C.setObjectName("trust_ip_C")
        self.trust_ip_C.addItem("")
        self.gridLayout_3.addWidget(self.trust_ip_C, 0, 1, 1, 1)
        self.server_ip_C = QtWidgets.QComboBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_ip_C.sizePolicy().hasHeightForWidth())
        self.server_ip_C.setSizePolicy(sizePolicy)
        self.server_ip_C.setMinimumSize(QtCore.QSize(150, 28))
        self.server_ip_C.setMaximumSize(QtCore.QSize(150, 28))
        self.server_ip_C.setObjectName("server_ip_C")
        self.gridLayout_3.addWidget(self.server_ip_C, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(150, 20))
        self.label_11.setMaximumSize(QtCore.QSize(150, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 4, 1, 1)
        self.cheat_port_T = QtWidgets.QPlainTextEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cheat_port_T.sizePolicy().hasHeightForWidth())
        self.cheat_port_T.setSizePolicy(sizePolicy)
        self.cheat_port_T.setMaximumSize(QtCore.QSize(50, 30))
        self.cheat_port_T.setObjectName("cheat_port_T")
        self.gridLayout_3.addWidget(self.cheat_port_T, 0, 5, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget5.setGeometry(QtCore.QRect(9, 295, 1021, 42))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(200, 20))
        self.label_16.setSizeIncrement(QtCore.QSize(200, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        self.http_view_T = QtWidgets.QPlainTextEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.http_view_T.sizePolicy().hasHeightForWidth())
        self.http_view_T.setSizePolicy(sizePolicy)
        self.http_view_T.setMinimumSize(QtCore.QSize(0, 30))
        self.http_view_T.setMaximumSize(QtCore.QSize(16777215, 30))
        self.http_view_T.setObjectName("http_view_T")
        self.gridLayout_7.addWidget(self.http_view_T, 0, 1, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget6.setGeometry(QtCore.QRect(9, 343, 1021, 42))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_8.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(200, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 0, 0, 1, 1)
        self.save_file_path_T = QtWidgets.QPlainTextEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_file_path_T.sizePolicy().hasHeightForWidth())
        self.save_file_path_T.setSizePolicy(sizePolicy)
        self.save_file_path_T.setMinimumSize(QtCore.QSize(0, 30))
        self.save_file_path_T.setMaximumSize(QtCore.QSize(16777215, 30))
        self.save_file_path_T.setObjectName("save_file_path_T")
        self.gridLayout_8.addWidget(self.save_file_path_T, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_8.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(16, 21, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 20))
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.need_scan_ip_T = QtWidgets.QPlainTextEdit(MainWindow)
        self.need_scan_ip_T.setEnabled(True)
        self.need_scan_ip_T.setGeometry(QtCore.QRect(222, 16, 141, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.need_scan_ip_T.sizePolicy().hasHeightForWidth())
        self.need_scan_ip_T.setSizePolicy(sizePolicy)
        self.need_scan_ip_T.setMaximumSize(QtCore.QSize(16777215, 30))
        self.need_scan_ip_T.setSizeIncrement(QtCore.QSize(0, 0))
        self.need_scan_ip_T.setPlainText("")
        self.need_scan_ip_T.setPlaceholderText("192.168.1.1/24")
        self.need_scan_ip_T.setObjectName("need_scan_ip_T")
        self.label_7 = QtWidgets.QLabel(MainWindow)
        self.label_7.setGeometry(QtCore.QRect(628, 21, 200, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(200, 20))
        self.label_7.setMaximumSize(QtCore.QSize(200, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.scan_type_C = QtWidgets.QComboBox(MainWindow)
        self.scan_type_C.setGeometry(QtCore.QRect(834, 17, 92, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_type_C.sizePolicy().hasHeightForWidth())
        self.scan_type_C.setSizePolicy(sizePolicy)
        self.scan_type_C.setMinimumSize(QtCore.QSize(0, 28))
        self.scan_type_C.setMaximumSize(QtCore.QSize(16777215, 28))
        self.scan_type_C.setObjectName("scan_type_C")
        self.scan_type_C.addItem("")
        self.scan_type_C.addItem("")
        self.start_scan_B = QtWidgets.QPushButton(MainWindow)
        self.start_scan_B.setGeometry(QtCore.QRect(932, 17, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_scan_B.sizePolicy().hasHeightForWidth())
        self.start_scan_B.setSizePolicy(sizePolicy)
        self.start_scan_B.setObjectName("start_scan_B")
        self.label_17 = QtWidgets.QLabel(MainWindow)
        self.label_17.setGeometry(QtCore.QRect(370, 21, 130, 20))
        self.label_17.setMinimumSize(QtCore.QSize(130, 20))
        self.label_17.setMaximumSize(QtCore.QSize(130, 20))
        self.label_17.setObjectName("label_17")
        self.send_card = QtWidgets.QComboBox(MainWindow)
        self.send_card.setGeometry(QtCore.QRect(481, 17, 151, 28))
        self.send_card.setMinimumSize(QtCore.QSize(0, 28))
        self.send_card.setMaximumSize(QtCore.QSize(16777215, 28))
        self.send_card.setObjectName("send_card")

        self.retranslateUi(MainWindow)
        self.pushButton_6.clicked.connect(MainWindow.chose_filepath)
        self.start_ip_cheat_B.clicked.connect(MainWindow.start_cheat)
        self.ARP_cheat_B.clicked.connect(MainWindow.start_arp_cheat)
        self.ARP_higher_B.clicked.connect(MainWindow.stop_attack)
        self.start_scan_B.clicked.connect(MainWindow.start_scan)
        self.start_attack_B.clicked.connect(MainWindow.start_attack)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IP欺骗设计"))
        self.label_3.setText(_translate("MainWindow", "请输入要扫描的端口"))
        self.label_8.setText(_translate("MainWindow", "请选择扫描的端口类型"))
        self.port_type_C.setItemText(0, _translate("MainWindow", "TCP端口"))
        self.port_type_C.setItemText(1, _translate("MainWindow", "UDP端口"))
        self.host_choice.setText(_translate("MainWindow", "主机扫描"))
        self.port_choice.setText(_translate("MainWindow", "端口扫描"))
        self.label_18.setText(_translate("MainWindow", "选择网关"))
        self.label_4.setText(_translate("MainWindow", "存活主机开启的端口"))
        self.label.setText(_translate("MainWindow", "存活的主机列表"))
        self.label_6.setText(_translate("MainWindow", "选择要欺骗的主机"))
        self.label_5.setText(_translate("MainWindow", "选择要欺骗的主机"))
        self.ARP_cheat_B.setText(_translate("MainWindow", "开始ARP欺骗"))
        self.ARP_higher_B.setText(_translate("MainWindow", "停止攻击"))
        self.attack_type_C.setItemText(0, _translate("MainWindow", "SYN洪泛"))
        self.attack_type_C.setItemText(1, _translate("MainWindow", "ICMP洪泛"))
        self.attack_type_C.setItemText(2, _translate("MainWindow", "UDP洪泛"))
        self.start_attack_B.setText(_translate("MainWindow", "开始攻击"))
        self.label_13.setText(_translate("MainWindow", "选择攻击方式"))
        self.label_14.setText(_translate("MainWindow", "输入对应的端口号"))
        self.label_12.setText(_translate("MainWindow", "输入要攻击的IP地址"))
        self.label_10.setText(_translate("MainWindow", "选择服务器IP"))
        self.start_ip_cheat_B.setText(_translate("MainWindow", "开始IP欺骗"))
        self.label_9.setText(_translate("MainWindow", "选择信任IP"))
        self.trust_ip_C.setItemText(0, _translate("MainWindow", "192.168.1.200"))
        self.label_11.setText(_translate("MainWindow", "输入对应的端口号"))
        self.label_16.setText(_translate("MainWindow", "输入要进行HTTP访问的路径"))
        self.http_view_T.setPlainText(_translate("MainWindow", "/"))
        self.label_15.setText(_translate("MainWindow", "输入文件保存的地址"))
        self.pushButton_6.setText(_translate("MainWindow", "选择路径"))
        self.label_2.setText(_translate("MainWindow", "请输入要扫描的iP"))
        self.label_7.setText(_translate("MainWindow", "请选择进行主机扫描的方式"))
        self.scan_type_C.setItemText(0, _translate("MainWindow", "ARP扫描"))
        self.scan_type_C.setItemText(1, _translate("MainWindow", "ICMP扫描"))
        self.start_scan_B.setText(_translate("MainWindow", "开始扫描"))
        self.label_17.setText(_translate("MainWindow", "请选择发包网卡"))
